name: server_nano
version: 1.1.0
homepage: http://github.com/jonataslaw/dart-server-nano
description: A light, fast, and friendly server written in dart.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mime: ^1.0.4
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
