name: server_nano_nano
version: 1.0.0
homepage: https://github.com/jonataslaw/dart-server-nano
description: A super light http server written in dart.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mime: ^1.0.5
  path: ^1.9.0
  collection: ^1.19.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.3
