name: server_nano
version: 1.0.0
homepage: http://github.com/jonataslaw/server_nano
description: A fast, friendly and powerful server for Dart and Flutter.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  mime: ^1.0.4
  path: ^1.8.3

dev_dependencies: 
  lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.16.5

